### ISSUE TITLE
The model yields blank images during training

### ISSUE THREAD

**Issue by neverstopZyy** [Enigmatisms/NeRF#8]
Hi!! Thanks for your efforts to reproduce the paper!
I find some mistakes with training on the datasets of materials, and the dataset looks like:
![image](https://user-images.githubusercontent.com/42933584/196699108-50f3066b-69f7-4144-8b9a-7c6d216152f1.png)

The model outputs blank and meaningless images, and I wonder How to fix it?
![image](https://user-images.githubusercontent.com/42933584/196698424-e436a76d-48cc-4f14-99ae-ab59889c2759.png)

**Comment by Enigmatisms** [comment]
Thank u for pointing this out. I never tested the whole dataset, only some of the objects that interested me were tested. I guess this phenomenon will happen a lot since I am a NeRF amateur, plus this repo is a mixture of a few approaches. I will be looking into this tomorrow.

**Comment by Enigmatisms** [comment]
I trained scene `materials` (from blender nerf synthetic dataset of original NERF, not RefNeRF shinny dataset), using the following configurations:
```shell
python3 ./train.py -s -t -u -w --sample_ray_num 1024 --dataset_name materials --render_depth --render_normal
```

Everything looks fine... I got proper PSNR and loss curves, and one output result (for 20 epochs):
![result_000](https://user-images.githubusercontent.com/46109954/196730398-2132a3ce-0dde-481c-9981-5665deed0b29.png)

Probable reasons for failure:
- Bad initialization. I didn't use fixed random seed, therefore each time you run this program, you'll get different network initialization. Sometimes it can be pretty awful and I guess getting a bad initialization which leads to awful gradient is not a small probability event (since, the mixture of approaches is somewhat unstable).
- Your param settings not being good enough. Also, if you tried multiple times and none of them succeeds, you should publish your param settings in the issue, and some detailed phenomena (like the printed PSNR and loss in your console), which helps me understand what is going on.
- I can't recall whether there is a `materials` scene in shinny dataset of RefNeRF (I deleted shinny dataset for lack of storage space). And if there is, maybe it is because I tested with the original NeRF synthetic dataset?

**Comment by Enigmatisms** [comment]
Unable to reproduce the phenomenon stated in this issue. Further information is required for reopenning this issue which has been inactive for days.
